apps/courseApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = 'delete'),
    url(r'^back', views.back, name = 'back'),
    url(r'^add', views.add, name = 'add'),
    url(r'^users_courses', views.courses, name = 'courses'),
    url(r'^newuser', views.adduser, name = 'adduser')
]

integration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.integration.urls')),
    url(r'^ninja_gold/', include('apps.ninjagold.urls', namespace = 'gold')),
    url(r'^survey/', include('apps.surveyForm.urls', namespace = 'survey')),
    url(r'^random/', include('apps.randomword.urls', namespace = 'random')),
    url(r'^login/', include('apps.loginApp.urls', namespace = 'login')),
    url(r'^courses/', include('apps.courseApp.urls', namespace = 'courses')),
]

apps/courseApp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Course(models.Model):
	title = models.CharField(max_length=255)
	description = models.TextField(max_length=255)
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)

apps/courseApp/views.py
from django.shortcuts import render, redirect
from .models import Course
from ..loginApp.models import User
from django.core.urlresolvers import reverse
from django.db.models import Count
# Create your views here.

def index(request):
	context = {
	"courses": Course.objects.all(),
	}
	return render(request, "courseApp/index.html", context)
	
def back(request):
	return redirect(reverse('courses:index'))

def remove(request, id):
	context = {
	"course": Course.objects.get(id=id)
	}
	return render(request, "courseApp/destroy.html", context)

def delete(request, id):
	Course.objects.get(id=id).delete()
	return redirect (reverse('courses:index'))

def add(request):
	name = request.POST["name"]
	desc = request.POST["description"]
	Course.objects.create(title=name,description=desc)
	return redirect(reverse('courses:index'))

def courses(request):
	context = {
	"courses": Course.objects.annotate(num_users = Count('users')),
	"users": User.objects.all(),
	}
	"""print "*"*80
	print context"""
	return render(request, "courseApp/users_courses.html", context)

def adduser(request):
	courseid = request.POST['courses']
	userid = request.POST['users']
	course = Course.objects.get(id = courseid)
	user = User.objects.get(id = userid)
	course.users.add(user)
	return redirect(reverse('courses:courses'))

apps/courseApp/templates/courseApp/destroy.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>Remove</title>
	</head>
	<body>
		<h1>Are You sure that you want to delete the following course?</h1>
		<table>
			<tr>
				<td>Name:</td>
				<td>{{course.title}}</td>
			</tr>
			<tr>
				<td>Description:</td>
				<td>{{course.description}}</td>
			</tr>
			<form action = "{% url 'courses:back' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "No">
			</form>
			<form action = "{% url 'courses:delete' course.id %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Yes! I want to delete this">
			</form>
		</table>
	</body>
</html>

apps/courseApp/templates/courseApp/index.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>Courses</title>
	</head>
	<body>
		<h1>Add a new course</h1>
		<form action = "{% url 'courses:add' %}" method = "post">
			{% csrf_token %}
			<label for "name">Name:</label>
			<input type = "text" name = "name" id = "name">
			<p>Description:</p>
			<textarea name = "description"></textarea>
			<input type = "submit" value = "Add">
		</form>
		<h1>Courses</h1>
		<table>
			<thead>
				<tr>
					<th>Course Name</th>
					<th>Description</th>
					<th>Date Added</th>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				{% for course in courses %}
					<tr>
						<td>{{course.title}}</td>
						<td>{{course.description}}</td>
						<td>{{course.created_at}}</td>
						<td>
							<form action = "{% url 'courses:remove' course.id %}" method = "post">
								{% csrf_token %}
								<input type = "submit" value = "remove">
							</form>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>

apps/courseApp/templates/courseApp/users_courses.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>User Courses</title>
	</head>
	<body>
		<form action = "{% url 'courses:adduser' %}" method = "post">
			{% csrf_token %}
			<label for="users">Users:</label>
			<select id = "users" name = "users">
				{% for user in users %}
					<option value = {{user.id}}>{{user.first_name}} {{user.last_name}}</option>
				{% endfor %}
			</select>
			<label for="courses">Courses:</label>
			<select id = "courses" name = "courses">
				{% for course in courses %}
					<option value = {{course.id}}>{{course.title}}</option>
				{% endfor %}
			</select>
			<input id = "button" type = "submit" value = "Add User to Course">
		</form>
		<table>
			<thead>
				<tr>
					<th>Course</th>
					<th>Title</th>
					<th>Number of Users</th>
				</tr>
			</thead>
			<tbody>
				{% for course in courses %}
					<tr>
						<td>{{course.id}}</td>
						<td>{{course.title}}</td>
						<td>{{course.num_users}}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</body>
</html>