apps/loginApp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^login', views.login, name = 'login'),
    url(r'^register', views.register, name = 'register'),
    url(r'^success', views.success, name = 'success')
]

integration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.integration.urls')),
    url(r'^ninja_gold/', include('apps.ninjagold.urls', namespace = 'gold')),
    url(r'^survey/', include('apps.surveyForm.urls', namespace = 'survey')),
    url(r'^random/', include('apps.randomword.urls', namespace = 'random')),
    url(r'^login/', include('apps.loginApp.urls', namespace = 'login')),
    url(r'^courses/', include('apps.courseApp.urls', namespace = 'courses')),
]

apps/loginApp/models.py
from __future__ import unicode_literals

from django.db import models
from ..courseApp.models import Course

import re
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here.
class UserManager(models.Manager):
	def validation(self,first, last, email, password, confirm):
		retlist = []
		##print "*"*80
		if len(first) < 2:
			##print "*"*40
			retlist.append("First Name Too Short.")
		if len(last) < 2:
			##print "*"*35
			retlist.append("Last Name Too Short.")
		if len(email) < 1:
			##print "*"*30
			retlist.append("Email Too Short.")
		elif not EMAIL_REGEX.match(email):
			##print "*"*25
			retlist.append("Invalid Email.")
		if len(password) < 8:
			##print "*"*20
			retlist.append("Password Too Short.")
		if password != confirm:
			##print "*"*15
			retlist.append("Password does not match confirmation.")
		if len(retlist) == 0:
			return "Success"
		return retlist

class User(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	courses = models.ManyToManyField(Course, related_name = "users")
	created_at = models.DateTimeField(auto_now_add = True)
	updated_at = models.DateTimeField(auto_now = True)
	objects = UserManager()

apps/loginApp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import User
import bcrypt
# Create your views here.
def index(request):
	return render(request, "loginApp/index.html")
	
def register(request):
	if not "hashes" in request.session:
		request.session["hashes"] = {}
	first = request.POST['first']
	last = request.POST['last']
	email = request.POST['email']
	password = request.POST['password']
	confirm = request.POST['confirm']
	check = User.objects.validation(first, last, email, password, confirm)
	if not check == "Success":
		for i in range(len(check)):
			messages.add_message(request, messages.INFO, check[i])
		return redirect(reverse('login:index'))
	password = password.encode(encoding = "utf-8")
	hashed = bcrypt.hashpw(password, bcrypt.gensalt())
	request.session["hashes"][password] = hashed
	request.session["name"] = first
	User.objects.create(first_name = first, last_name = last, email = email, password = hashed)
	return redirect(reverse('login:success'))
	
def login(request):
	email = request.POST['email']
	password = request.POST['password']
	password = password.encode(encoding = "utf-8")
	"""print "*"*80
	print password"""
	if not "hashes" in request.session:
		request.session["hashes"] = {}
	"""print "*"*80
	print request.session["hashes"]"""
	if not password in request.session["hashes"]:
		messages.add_message(request, messages.INFO, "Invalid Password")
		return redirect(reverse('login:index'))
	##print "*"*80
	hashed = bcrypt.hashpw(password, request.session["hashes"][password].encode(encoding = "utf-8"))
	query = User.objects.filter(email=email).filter(password=hashed)
	if len(query) < 1:
		messages.add_message(request, messages.INFO, "Invalid Credentials")
		return redirect(reverse('login:index'))
	request.session["name"] = query[0].first_name
	return redirect(reverse('login:success'))
	

def success(request):
	return render(request, "loginApp/success.html")

apps/loginApp/templates/loginApp/index.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>Email</title>
	</head>
	<body>
		{% if messages %}
			{% for message in messages %}
				<p>{{ message }}</p>
			{% endfor %}
		{% endif %}
		<h2>Registration</h2>
		<form action = "{% url 'login:register' %}" method = "post">
			{% csrf_token %}
			<label>First Name:<input type = "text" name = "first" id = "first"></label>
			<label>Last Name:<input type = "text" name = "last" id = "last"></label>
			<label>Email:<input type = "text" name = "email" id = "email"></label>
			<label>Password:<input type = "password" name = "password" id = "password"></label>
			<label>Confirm pw:<input type = "password" name = "confirm" id = "confirm"></label>
			<input type = "submit" value = "Register">
		</form>
		<h2>Login</h2>
		<form action = "{% url 'login:login' %}" method = "post">
			{% csrf_token %}
			<label>Email:<input type = "text" name = "email" id = "logemail"></label>
			<label>Password:<input type = "password" name = "password" id = "logpassword"></label>
			<input type = "submit" value = "Login">
		</form>
	</body>
</html>

apps/loginApp/templates/loginApp/success.html
<!DOCTYPE HTML>
<html>
  <head>
  	<meta charset="UTF-8">
  	<title>Success</title>
  </head>
  <body>
    <h1>Success! Welcome, {{request.session.name}}!</h1>
    <h2>Successfully registered or logged in!</h2>
  </body>
  </html>