apps/ninjagold/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^farm$', views.farm, name = "farm"),
    url(r'^cave$', views.cave, name = "cave"),
    url(r'^house$', views.house, name = "house"),
    url(r'^casino$', views.casino, name = "casino")
]

integration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.integration.urls')),
    url(r'^ninja_gold/', include('apps.ninjagold.urls', namespace = 'gold')),
    url(r'^survey/', include('apps.surveyForm.urls', namespace = 'survey')),
    url(r'^random/', include('apps.randomword.urls', namespace = 'random')),
    url(r'^login/', include('apps.loginApp.urls', namespace = 'login')),
    url(r'^courses/', include('apps.courseApp.urls', namespace = 'courses')),
]

apps/ninjagold/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/ninjagold/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from django.core.urlresolvers import reverse
import random

# Create your views here.
def index(request):
	if not 'gold' in request.session:
		request.session['gold'] = 50
	if not 'activities' in request.session:
		request.session['activities'] = ""
	return render(request, "ninjagold/index.html")
	
def farm(request):
	current = datetime.today()
	number = random.randrange(10,21)
	request.session['gold'] += number
	time = "(" + current.strftime("%x") + " " + current.strftime("%-I") + ":" + current.strftime("%M") + " " + current.strftime("%p") + ")"
	request.session['activities'] = request.session['activities'] + "<span class = 'green'>Earned {} gold! {}</span><br>".format(number, time)
	return redirect(reverse('gold:index'))
	
def cave(request):
	current = datetime.today()
	number = random.randrange(5,11)
	request.session['gold'] += number
	time = "(" + current.strftime("%x") + " " + current.strftime("%-I") + ":" + current.strftime("%M") + " " + current.strftime("%p") + ")"
	request.session['activities'] = request.session['activities'] + "<span class = 'green'>Earned {} gold! {}</span><br>".format(number, time)
	return redirect(reverse('gold:index'))
	
def house(request):
	current = datetime.today()
	number = random.randrange(2,6)
	request.session['gold'] += number
	time = "(" + current.strftime("%x") + " " + current.strftime("%-I") + ":" + current.strftime("%M") + " " + current.strftime("%p") + ")"
	request.session['activities'] = request.session['activities'] + "<span class = 'green'>Earned {} gold! {}</span><br>".format(number, time)
	return redirect(reverse('gold:index'))
	
def casino(request):
	current = datetime.today()
	number = random.randrange(-50,50)
	if request.session['gold'] + number < 0:
		request.session['gold'] = 0
	else:
		request.session['gold'] += number
	time = "(" + current.strftime("%x") + " " + current.strftime("%-I") + ":" + current.strftime("%M") + " " + current.strftime("%p") + ")"
	if number >= 0:
		request.session['activities'] += "<span class = 'green'>Earned {} gold! {}</span><br>".format(number,time)
	else:
		request.session['activities'] += "<span class = 'red'>Lost {} gold! {}</span><br>".format(number * -1, time)
	return redirect(reverse('gold:index'))
	

apps/ninjagold/templates/ninjagold/index.html
<!DOCTYPE HTML>
<html>
  <head>
  	<meta charset="UTF-8">
  	{% load staticfiles %}
  	<link rel="stylesheet" type="text/css" href="{% static 'ninjagold/css/main.css' %}">
  </head>
  <body>
  	<div id = "mainwrapper">
		<p>Your Gold: {{request.session.gold}}</p>
		<div class = "box">
			<h2>Farm</h2>
			<p>(earns 10-20 gold)</p>
			<form id = farm action = "{% url 'gold:farm' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Find Gold!">
			</form>
		</div>
		<div class = "box">
			<h2>Cave</h2>
			<p>(earns 5-10 gold)</p>
			<form id = cave action = "{% url 'gold:cave' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Find Gold!">
			</form>
		</div>
		<div class = "box">
			<h2>House</h2>
			<p>(earns 2-5 gold)</p>
			<form id = house action = "{% url 'gold:house' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Find Gold!">
			</form>
		</div>
		<div class = "box">
			<h2>Casino</h2>
			<p>(earns/takes 0-50 gold)</p>
			<form id = casino action = "{% url 'gold:casino' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Find Gold!">
			</form>
		</div>
		<div id = "wrapper">
			<p>Activities:</p>
			<div id = "activities">
				<p>{{request.session.activities|safe}}</p>
			</div>
		</div>
	</div>
  </body>
</html>