apps/surveyForm/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^submit', views.submit, name = 'submit'),
    url(r'^result', views.result, name = 'result'),
    url(r'^back', views.back, name = 'back')
]

integration_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.integration.urls')),
    url(r'^ninja_gold/', include('apps.ninjagold.urls', namespace = 'gold')),
    url(r'^survey/', include('apps.surveyForm.urls', namespace = 'survey')),
    url(r'^random/', include('apps.randomword.urls', namespace = 'random')),
    url(r'^login/', include('apps.loginApp.urls', namespace = 'login')),
    url(r'^courses/', include('apps.courseApp.urls', namespace = 'courses')),
]

apps/surveyForm/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/surveyForm/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
	return render(request, 'surveyForm/index.html')
	
def back(request):
	return redirect(reverse('survey:index'))

def result(request):
	return render(request, 'surveyForm/success.html')

def submit(request):
	if request.method == "POST":
		request.session['name'] = request.POST['name']
		request.session['dojo'] = request.POST['dojo']
		request.session['language'] = request.POST['language']
		request.session['comment'] = request.POST['comment']
		if not 'number' in request.session:
			request.session['number'] = 0
		request.session['number'] += 1
	return redirect(reverse('survey:result'))

apps/surveyForm/templates/surveyForm/index.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>Random Word</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'surveyForm/css/main.css' %}" media="screen" title="no title">
	</head>
	<body>
		<div id = "wrapper">
			<form action = "{% url 'survey:submit' %}" method = "post">
				{% csrf_token %}
				<label for="name">Your Name:</label>
				<input type="text" name="name" id="name"</label>
				<label for="dojo">Dojo Location:</label>
				<select id = "dojo" name = "dojo">
					<option value = "Seattle">Seattle</option>
					<option value = "New York">New York</option>
					<option value = "Los Angeles">Los Angeles</option>
				</select>
				<label for="language">Favorite language:</label>
				<select id = "language" name = "language">
					<option value = "Ruby">Ruby</option>
					<option value = "C#">C#</option>
					<option value = "BASIC">BASIC</option>
				</select>
				<p>Comment (optional)</p>
				<textarea name = "comment"></textarea>
				<input type = "submit" name = "submit" value = "Submit">
			</form>
		</div>
	</body>
</html>

apps/surveyForm/templates/surveyForm/success.html
<!DOCTYPE html>
<html lang = "en">
	<head>
		<meta charset = "UTF-8">
		<title>Random Word</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'surveyForm/css/success.css' %}" media="screen" title="no title">
	</head>
	<body>
		<div id = "header">
			<p>Thanks for submitting this form!  You have submitted this form {{request.session.number}} times now.</p>
		</div>
		<div id = "wrapper">
			<p><span id = "underline">Submitted Information</span></p>
			<table>
				<thead>
				</thead>
				<tbody>
					<tr>
						<td>Name:</td>
						<td>{{request.session.name}}</td>
					</tr>
					<tr>
						<td>Dojo Location:</td>
						<td>{{request.session.dojo}}</td>
					</tr>
					<tr>
						<td>Favorite Language:</td>
						<td>{{request.session.language}}</td>
					</tr>
					<tr>
						<td>Comment:</td>
						<td>{{request.session.comment}}</td>
					</tr>
				</tbody>
			</table>
			<form action = "{% url 'survey:back' %}" method = "post">
				{% csrf_token %}
				<input type = "submit" value = "Go Back">
			</form>
		</div>
	</body>
</html>